create table amusement_park (
        entrance_fee integer not null check ((entrance_fee>=5) and (entrance_fee<=200)),
        id bigint generated by default as identity,
        name varchar(50) not null unique,
        owner_name varchar(255),
        primary key (id)
    );
create table amusement_park_know_user (
        amusement_park_id bigint not null,
        date_of_first_enter timestamp(6),
        user_name varchar(255) not null,
        primary key (amusement_park_id, user_name)
    );
create table guest_book_registry (
        amusement_park_id bigint not null,
        date_of_registry timestamp(6),
        id bigint generated by default as identity,
        text_of_registry varchar(100) not null,
        user_name varchar(255) not null,
        primary key (id)
    );
create table machine (
        minimum_required_age integer not null check ((minimum_required_age>=0) and (minimum_required_age<=21)),
        ticket_price integer not null check ((ticket_price>=1) and (ticket_price<=30)),
        video_length_in_seconds integer not null check ((video_length_in_seconds>=5) and (video_length_in_seconds<=400)),
        amusement_park_id bigint not null,
        id bigint generated by default as identity,
        fantasy_name varchar(50) not null unique,
        video varchar(255) not null,
        primary key (id)
    );
create table photo (
        id bigint generated by default as identity,
        photo oid,
        primary key (id)
    );
create table users (
        coupon integer not null check ((coupon>=0) and (coupon<=9223372036854775807)),
        date_of_birth date not null,
        is_activated_coupon boolean not null,
        money integer not null check ((money>=0) and (money<=9223372036854775807)),
        amusement_park_id bigint,
        date_of_sign_up timestamp(6),
        machine_id bigint,
        photo_id bigint unique,
        authority varchar(25) not null,
        name varchar(50) not null,
        password varchar(60) not null,
        primary key (name)
    );
alter table if exists amusement_park
       add constraint FK72ymtlduj73qvvtk85l5pavtb
       foreign key (owner_name)
       references users;
alter table if exists amusement_park_know_user
       add constraint FKsu1407dsytt1tj041q6scve5i
       foreign key (amusement_park_id)
       references amusement_park;
alter table if exists amusement_park_know_user
       add constraint FK8kinkfdsxoxlewajl4tl6x21e
       foreign key (user_name)
       references users;
alter table if exists guest_book_registry
       add constraint FKsx0gf40kmm8f7h17sf2ru43ev
       foreign key (amusement_park_id)
       references amusement_park;
alter table if exists guest_book_registry
       add constraint FK7x9w85tvaff6no9fq8gkbmqrv
       foreign key (user_name)
       references users;
alter table if exists machine
       add constraint FK4sw7jc6c5kqbeee41r6g5v3wp
       foreign key (amusement_park_id)
       references amusement_park;
alter table if exists users
       add constraint FKm5ec9jcwwstq3wpxxik4b8c1c
       foreign key (amusement_park_id)
       references amusement_park;
alter table if exists users
       add constraint FKsyy27jpav5fn1ijs0sag9c4m2
       foreign key (machine_id)
       references machine;
alter table if exists users
       add constraint FKpub9rq626qubh4iwiqr5ltiq5
       foreign key (photo_id)
       references photo;

CREATE TABLE SPRING_SESSION (
	PRIMARY_ID CHAR(36) NOT NULL,
	SESSION_ID CHAR(36) NOT NULL,
	CREATION_TIME BIGINT NOT NULL,
	LAST_ACCESS_TIME BIGINT NOT NULL,
	MAX_INACTIVE_INTERVAL INT NOT NULL,
	EXPIRY_TIME BIGINT NOT NULL,
	PRINCIPAL_NAME VARCHAR(100),
	CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
	SESSION_PRIMARY_ID CHAR(36) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES BYTEA NOT NULL,
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);
